### ISSUE TITLE
on first use, don't fetch 'many/all' mails, only a configurable number (e.g. 10-15)

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-webmail#2]
@tari01: I just set up Ayatana Webmail and I have a very large INBOX. It fetched quite a few mails (more than what could be fitted on one screen). I'd say, on first check of an IMAP acocunt / folder, it would be good to limit the fetch mails to a configurable number (e.g. 10-15).

**Comment by ghost** [comment]
Ayatana Webmail's default fetch is no more than 20 mails. If you get exactly 20, then it's working as it should. If you get more, then we have a bug. Does it fetch more than 20 mails?

The dconf key for this is **/org/ayatana/webmail/max-item-count**

You can change the default with:
`gsettings set org.ayatana.webmail max-item-count 20`

It's not included in the UI to avoid clutter, since average users are unlikely to mess with this.

**Comment by sunweaver** [comment]
It gets 20 per selected INBOX'ish folder... I selected three folders and got 60 new mails.

**Comment by ghost** [comment]
Aha! Finally a proper bug to fix.

**Comment by ghost** [comment]
Resolved by https://github.com/AyatanaIndicators/ayatana-webmail/commit/5d48084eea23372948b0d768eeffdb83891c2d54

Another fix in the pipeline regarding this.
