### ISSUE TITLE
don't advertise GMail service

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-webmail#3]
Personally, I am not a fan of the GMail service. I think, we should not advertise it when Ayatana Webmail starts up for the first time.

**Comment by ghost** [comment]
You're talking to a person who uses DuckDuckGo, and runs LineageOS and F-Droid on his phone without GApps.

The problem is that most of our users use GMail. I will gladly get rid of the GMail strings and replace them with example.com, for now. We'll hold back new releases until #4 has a few options.

**Comment by sunweaver** [comment]
> You're talking to a person who uses DuckDuckGo, and runs LineageOS and F-Droid on his phone without GApps.

I'd thought so and wondered why suddenly GMail.

> The problem is that most of our users use GMail. I will gladly get rid of the GMail strings and replace them with example.com, for now. We'll hold back new releases until #4 has a few options.

Yeah, #4 is the proper counter recipe against this.

**Comment by ghost** [comment]
Resolved by https://github.com/AyatanaIndicators/ayatana-webmail/commit/71e54c50543d16580f0b18b89bf467629682aafe
